version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
      # @types/dompurify is deprecated as DOMPurify now includes its own types
      - dependency-name: "@types/dompurify"
      # node-fetch v3+ is ESM-only and breaks our CommonJS test setup
      - dependency-name: "node-fetch"
        versions: [">=3.0.0"]
      # Zod v4 is incompatible with OpenAI SDK v5.16.0 which requires Zod v3 as peer dependency
      - dependency-name: "zod"
        versions: [">=4.0.0"]
    groups:
      dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "eslint*"
          - "@types/*"
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      types:
        patterns:
          - "@types/*"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5