name = "cnd2-app"
compatibility_date = "2025-01-25"
pages_build_output_dir = ".next"

# Function bindings for Workers KV
[[kv_namespaces]]
binding = "CND2_RESULTS"
id = "623832c2612f48948daa625eacf29792"
preview_id = "b9f1e0af78a14ebcbfab872fb4764281"