name: Deploy to Cloudflare Pages (Production)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install npm dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        env:
          CI: true
          
      - name: Run linting checks
        run: npm run lint
        
      - name: Run TypeScript type checking
        run: npm run type-check
        
      - name: Create production environment file
        run: |
          echo "NEXT_PUBLIC_APP_URL=https://cnd2.cloudnativedays.jp" >> .env.production
          echo "PRAIRIE_CARD_BASE_URL=https://prairie-card.cloudnativedays.jp" >> .env.production
          
      - name: Build Next.js application
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: production
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # --commit-dirty=true: ビルドプロセスで生成されたファイル（.env.production等）を含めてデプロイ
          # --commit-message: UTF-8エンコーディング問題を回避するためASCII文字のみ使用
          # --commit-hash: Cloudflare側でデプロイを追跡するため明示的に指定
          command: pages deploy out --project-name=cnd2-app --commit-dirty=true --commit-message="Deploy from GitHub Actions - SHA ${{ github.sha }}" --commit-hash="${{ github.sha }}"