name: Deploy to Cloudflare Pages (Production)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install npm dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        env:
          CI: true
        continue-on-error: true
          
      - name: Run linting checks (non-blocking)
        run: npm run lint || true
        
      - name: Run TypeScript type checking
        run: npm run type-check
        continue-on-error: true
        
      - name: Create production environment file
        run: |
          echo "NEXT_PUBLIC_APP_URL=https://cdn2.cloudnativedays.jp" >> .env.production
          echo "PRAIRIE_CARD_BASE_URL=https://prairie-card.cloudnativedays.jp" >> .env.production
          
      - name: Build Next.js application
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: production
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cnd2-app
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
        env:
          # Avoid UTF-8 issues with commit messages
          CF_PAGES_COMMIT_SHA: ${{ github.sha }}