name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create .env.production
        run: |
          echo "NEXT_PUBLIC_APP_URL=https://cdn2.cloudnativedays.jp" >> .env.production
          echo "PRAIRIE_CARD_BASE_URL=https://prairie-card.cloudnativedays.jp" >> .env.production
          
      - name: Build application
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NODE_ENV: production
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true # Allow build errors for now
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cnd2-app
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          deploymentName: Production
          wranglerVersion: '3'